# Generated by Django 3.1.7 on 2021-03-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_value',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_available_funds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(),
        ),
    ]
