# Generated by Django 3.1.7 on 2021-03-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_stock_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
