# Generated by Django 3.1.7 on 2021-03-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_stock_stock_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_value',
            new_name='stock_cost',
        ),
    ]
